#!/bin/bash

INPUT=$2

quick() {
	# download tld_list.txt if not exist
	if [ ! -f "tld_list.txt" ]; then
	    curl -s "https://www.iana.org/domains/root/db" | grep -oP '\.\w+(?=<\/a>)' >> tld_list.txt
	fi
	for tld in $(cat tld_list.txt);do echo "$INPUT$tld" | filter-resolved >> "$INPUT"_tld.txt;done
}

verbose_mode() {
	# download tld_list.txt if not exist
	if [ ! -f "tld_list.txt" ]; then
	    curl -s "https://www.iana.org/domains/root/db" | grep -oP '\.\w+(?=<\/a>)' >> tld_list.txt

	fi
	python3 main.py
	cat tld_list.txt >> tld_combinations.txt
	for tld in $(cat tld_combinations.txt);do echo "$INPUT$tld" | filter-resolved >> "$INPUT"_tld.txt;done
}

showhelp(){
	echo -e "Quick-Mode Run:"
    echo -e "   bash tldscan -q google"
    echo -e ""
    echo -e "Verbose-Mode Run:"
    echo -e "   bash tldscan -v google"
    echo -e ""
    echo -e "Show Help:"
    echo -e "   bash tldscan -h"
    echo -e ""
}

# Check the function argument and call the respective function
if [ "$1" == "-q" ]; then
  	quick
elif [ "$1" == "-v" ]; then
  	verbose_mode
elif [ "$1" == "-h" ]; then
  	showhelp
else
  	echo "Invalid function name"
fi